### ISSUE TITLE
genesisvision.properties file missing

### ISSUE THREAD

**Issue by nishant304** [GenesisVision/android-client#1]
genesisvision.properties file missing, so unable to compile code

**Comment by vitaliiprus** [comment]
Hi! This file contains sensitive data, such as api addresses and keystore passwords, so it is ignored. You can create your own genesisvision.properties file in project root with the following example:

apiAddress="localhost"
tournamentApiAddress="localhost"
keystore=/path/to/.jks
keystore.password=keystore_password
keyAlias=alias
keyPassword=key_password

**Comment by nishant304** [comment]
Thanks for the response vitaly, but I dont have server at localhost.

It will be really nice if there was some docs/guidelines for contribution in case you guys are accepting one.
